# SELF-PACED LEARNING 3

## LIST

In [1]:
my_list = [1,2,3]

In [2]:
print(my_list)

[1, 2, 3]


In [3]:
my_list + 4 #error

TypeError: can only concatenate list (not "int") to list

In [4]:
my_list + [4, 5]

[1, 2, 3, 4, 5]

In [5]:
print(my_list * 2)

[1, 2, 3, 1, 2, 3]


method : append untuk menambah 1 isi

In [6]:
my_list.append(4)

In [7]:
print(my_list)

[1, 2, 3, 4]


menambahkan 2 atau lebih data secara langsung ke dalam list :

In [8]:
my_list.append(4, 5) #error 2 given

TypeError: list.append() takes exactly one argument (2 given)

In [9]:
my_list.append([4, 5])

In [10]:
print(my_list)

[1, 2, 3, 4, [4, 5]]


method : extend untuk menambah beberapa data secara langsung ke dalam sebuah variabel

In [11]:
mylist = [1,2,3]
print(mylist)

[1, 2, 3]


In [12]:
mylist.extend([4,5,6])
print(mylist)

[1, 2, 3, 4, 5, 6]


menghapus item. method : remove

In [13]:
#menghapus angka 4 dari my_list
mylist.remove(4)
print(mylist)

[1, 2, 3, 5, 6]


In [14]:
#menghapus list di dalam list
print(my_list)

[1, 2, 3, 4, [4, 5]]


In [15]:
my_list.remove([4,5])

In [16]:
print(my_list)

[1, 2, 3, 4]


## Dictionaries

In [17]:
student = {}

In [18]:
student = {'name' : 'firya', 'age' : 18}

In [19]:
employee = {'cto' : {'name' : 'firya' ,  'age' : 18}}

#deklarasi string : str()

In [20]:
student = dict(name = 'Seungmin', age=38)

In [21]:
print(student['name'])

Seungmin


In [22]:
print(student['age'])

38


ganti isi "="
menghapus data : delete (del)

In [23]:
print(student)

{'name': 'Seungmin', 'age': 38}


In [24]:
del student['age']

In [25]:
print(student)

{'name': 'Seungmin'}


In [26]:
student = {'name' : 'firya', 'age' : 17}

In [27]:
print(student.keys())

dict_keys(['name', 'age'])


In [28]:
print(student.values())

dict_values(['firya', 17])


## Tuples

In [29]:
people = ('Raka',('kode', 'random'))

In [30]:
print(people)

('Raka', ('kode', 'random'))


In [33]:
# mengakses informasi dalam tuples : menggunakan indeks
print(people[0])
print(people[1])
print(people[1][0])

Raka
('kode', 'random')
kode


In [34]:
numbers = (1,2,3,4)

In [35]:
new_numbers = numbers[0], numbers[1:3]

In [36]:
print(new_numbers)

(1, (2, 3))


In [37]:
print(numbers) #tetap

(1, 2, 3, 4)


Shorting :

In [38]:
email_attr = ('to', 'from', 'cc', 'bcc', 'subject', 'body')

In [39]:
# diubah menjadi list
email_attr_list = list(email_attr)

In [40]:
# diurutkan :
email_attr_list.sort()

In [41]:
print(email_attr_list)

['bcc', 'body', 'cc', 'from', 'subject', 'to']


 ## Files

In [42]:
myfile = open('textspc3', 'w')

In [43]:
myfile.write('halo text file!\n')

16

In [44]:
myfile.write('selamat tinggal text file!\n')

27

In [45]:
myfile.close()

In [47]:
myfile = open('textspc3')

In [48]:
myfile.readline()

'halo text file!\n'

In [49]:
myfile.readline()

'selamat tinggal text file!\n'

In [50]:
open('textspc3').read()

'halo text file!\nselamat tinggal text file!\n'

In [51]:
print(open('textspc3').read())

halo text file!
selamat tinggal text file!



In [55]:
x, y, z = 43, 44, 45
message = 'Spam'
data = {'a':1, 'b':2}
list = [1,2,3]

In [57]:
file = open('textspc3','w')

In [58]:
file.write(message + '\n')

5

In [59]:
file.write('%s, %s, %s\n' % (x, y, z))

11

In [63]:
# konversi list menjadi string
file.write(str(list) + '$' + str(data) + '\n')

27

In [64]:
file.close()

In [66]:
student = {1 : {'name': 'Idaz', 'age' : '27', 'sex' : 'Male'}, 
         2 : {'name': 'Emma', 'age' : '22', 'sex' : 'Female'}}

In [67]:
student[0][1]

KeyError: 0

In [68]:
student[1]["age"]

'27'

In [69]:
student[0]["age"]

KeyError: 0

In [65]:
aTuple = (100, 200, 300, 400)
aTuple[1] = 800
print(aTuple)

TypeError: 'tuple' object does not support item assignment

# Looping
## While

In [71]:
# menampilkan pesan dengan effect seperti echo
message = "spam"

In [72]:
while message != '' :
    print(message, end = ' ')
    message = message[1:]

spam pam am m 

In [73]:
a = 0
b = 13
while a < b :
    print(a, end=' ')
    a = a + 1

0 1 2 3 4 5 6 7 8 9 10 11 12 

In [ ]:
while True :
    name = input('Enter name : ')
    if name == 'stop' : break
    age = input (' Enter age :')
    print ('Hello', name, '=>', int(age) ** 2)

## for

In [76]:
for word in ['raka', 'billy','kode'] :
    print(word, end='\n')

raka
billy
kode


In [78]:
sum = 0

In [79]:
for i in [1, 2, 3, 4] :
    sum = sum + i

In [80]:
sum

10

In [81]:
prod = 1

In [82]:
for item in [1,2,3,4] : prod *= item

In [83]:
prod

24

In [84]:
# string
text = 'foxy fox'
words = ('is', 'great', 'animal')

In [85]:
for chara in text: print(chara, end=' ')

f o x y   f o x 

In [86]:
for word in words : print (word, end = '...')

is...great...animal...

pattern matching

In [87]:
coor = [(1,2), (3,4), (5,6)]

In [88]:
# melakuka pemetaan dari data coor dengan struktur data list tuple
for (x,y) in coor : 
    print(x,y)

1 2
3 4
5 6


In [90]:
x = 0
while (x < 100) :
    x+=2
print(x)

100


In [94]:
for l in 'Idaz':
    if l == 'a':
        pass
    print(l, end=", ")

I, d, a, z, 

# IF

In [95]:
if 1 :
    print ('true')
# angka 1 merupakan kondisi boolean true

true


In [96]:
if not 1 :
    print ('true')
else :
    print('false')

false


In [101]:
age = input('Enter your age')
if int(age) * 365 > 20000 :
    print('Time to retire!')
elif int(age) * 365 > 10000 :
    print('Lots of time left!')
else :
    print('Time to get Started!')

Enter your age78
Time to retire!


In [103]:
user_age = input('Enter your age: ')
age = int(user_age) * 365

if age >= 9490 :
    print('You are a Jedi Master now. Go Learn from Master Yoda!!')
elif age >= 8395 and age < 9490 :
    print('Becoming Jedi Knight')
else :
    print('You are a young Padawan')

Enter your age: 45
You are a Jedi Master now. Go Learn from Master Yoda!!


In [105]:
x = 10
y = 50


In [106]:
if (x**2 >100 and y<100) :
    print(x,y)

# Function

In [107]:
def add(a, b) :
    return a + b

In [108]:
add(5,4)

9

In [109]:
add_things = add(10, 4)

In [110]:
print(add_things)

14


In [111]:
# tidak melakukan return :
def add_and_print(a,b) :
    print(a + b)

In [112]:
add_and_print(1,3)

4


In [113]:
x = add_and_print(5,3)

8


In [114]:
print(x)

None


Fungsi yang akan mencari karakter yang sama yang terdapat dalam 2 kata

In [115]:
def intersection(first_word, second_word) :
    result = []
    for x in first_word : 
        if x in second_word :
            result.append(x)
    return result


In [116]:
word1 = 'spam'
word2 = 'scam'

In [117]:
char_of_intersect = intersection(word1, word2)

In [118]:
print(char_of_intersect)

['s', 'a', 'm']


## Bulit in function and modules

In [119]:
# menghasilkan nilai absolute pada sebuah angka
print(abs(-123))

123


In [122]:
# mencari tahu tipe data / struktur data dari sebuah variabel
numbers = [1,2,3]

In [125]:
print(isinstance(numbers, dict))

False


In [129]:
number = 22

In [132]:
print(isinstance(number, int))

True


In [134]:
# mencari nilai terbesar dan terkecil
numbers = [1,2,3,4,5,6]
print(max(numbers))
print(min(numbers))

6
1


In [135]:
alphas = ['a','b','z']
print(max(alphas))
print(min(alphas))

z
a


Built in methods

In [136]:
# list
# index 
language = ['py', 'js', 'go', 'c']
print(language.index('go'))

2


In [138]:
#sort 
language.sort()
print(language)

['c', 'go', 'js', 'py']


In [139]:
name = 'raka'
print(name)

raka


In [140]:
name.replace('k','c')

'raca'

In [142]:
name.capitalize()

'Raka'

In [175]:
name.upper()

'RAKA'

## Moduls

In [143]:
import b

In [144]:
b.logger('aku kamu kita')

Log:  aku kamu kita


In [145]:
import math

In [146]:
print(math.factorial(3))

6


In [151]:
from math import factorial
print(factorial(3))

6


In [147]:
from b import logger
logger('aku kamu kita')

Log:  aku kamu kita


## Packages

In [157]:
import requests 

In [158]:
r = requests.get('https://api.github.com/events')

In [159]:
print(r.status_code)

200


In [160]:
print(r.json())

[{'id': '20517176958', 'type': 'PullRequestEvent', 'actor': {'id': 17924565, 'login': 'rajendranr-5483', 'display_login': 'rajendranr-5483', 'gravatar_id': '', 'url': 'https://api.github.com/users/rajendranr-5483', 'avatar_url': 'https://avatars.githubusercontent.com/u/17924565?'}, 'repo': {'id': 444686578, 'name': 'syncfusion-content/ej2-asp-core-mvc-docs', 'url': 'https://api.github.com/repos/syncfusion-content/ej2-asp-core-mvc-docs'}, 'payload': {'action': 'closed', 'number': 145, 'pull_request': {'url': 'https://api.github.com/repos/syncfusion-content/ej2-asp-core-mvc-docs/pulls/145', 'id': 867840829, 'node_id': 'PR_kwDOGoFg8s4zujM9', 'html_url': 'https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/145', 'diff_url': 'https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/145.diff', 'patch_url': 'https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/145.patch', 'issue_url': 'https://api.github.com/repos/syncfusion-content/ej2-asp-core-mvc-docs/issue

In [172]:
#quiz
def outerFun(a,b):
    def innerFun(c,d):
        return c + d
    return innerFun(a,b)
res = outerFun(5,10) 
print(res)

15


 # Numpy

In [178]:
height = [1.75, 1.68, 1.8, 1.81, 1.69]
weight = [66.4, 49.22, 66.3, 88.56, 65.4]
weight/ height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [177]:
import numpy as np

In [180]:
height = [1.75, 1.68, 1.8, 1.81, 1.69]
weight = [66.4, 49.22, 66.3, 88.56, 65.4]
np_height = np.array(height)
np_weight = np.array(weight)
bmi = np_weight/np_height ** 2

In [181]:
print(bmi)

[21.68163265 17.43905896 20.46296296 27.03214188 22.8983579 ]


hanya dapat menampung 1 tipe data, apabila memiliki tipe data yang berbeda maka akan dikonversi menjadi 1 tipe data yang sama (string). 

In [182]:
mixed_array = np.array([1.0, 'is', True])
print(mixed_array)

['1.0' 'is' 'True']


menjumlahkan isi array

In [183]:
numlist = [1,2,3]
nparray = np.array([1,2,3])
numlist + numlist

[1, 2, 3, 1, 2, 3]

In [184]:
bmi

array([21.68163265, 17.43905896, 20.46296296, 27.03214188, 22.8983579 ])

In [185]:
bmi > 24

array([False, False, False,  True, False])

In [186]:
bmi[bmi>24]

array([27.03214188])

## Array 2D

In [187]:
height = np.array([1.75, 1.68, 1.8])
weight = np.array([66.4, 49.22, 66.3])
type(height)

numpy.ndarray

In [189]:
np_2d = np.array ([[1.75, 1.68, 1.8],
                  [66.4, 49.22, 66.3]])
np_2d

array([[ 1.75,  1.68,  1.8 ],
       [66.4 , 49.22, 66.3 ]])

In [190]:
np_2d.shape

(2, 3)

In [193]:
# subsetting
print(np_2d[0])
print(np_2d[0][2])

[1.75 1.68 1.8 ]
1.8


In [194]:
np_2d[:,1:3]

array([[ 1.68,  1.8 ],
       [49.22, 66.3 ]])

In [195]:
np_2d[1,:]

array([66.4 , 49.22, 66.3 ])

In [206]:
names = np.array([['idaz','anggara'],
                 ['dear', 'kurniawan']])
print(names[0])
print(names[[0]])
print(names(0))

['idaz' 'anggara']
[['idaz' 'anggara']]


TypeError: 'numpy.ndarray' object is not callable

## Statistik Dasar dengan Numpy

In [196]:
height = np.round(np.random.normal(1.73, 0.2, 5000),2)
height

array([1.74, 2.17, 1.63, ..., 1.56, 1.92, 1.61])

In [197]:
len(height)

5000

In [198]:
weight = np.round(np.random.normal(60.32, 15, 5000),2)
weight

array([67.02, 51.94, 72.89, ..., 84.87, 80.64, 65.57])

In [199]:
len(weight)

5000

In [200]:
np_city = np.column_stack((height, weight))

In [203]:
np.mean(np_city[:,0])

1.732074

In [202]:
np.mean(np_city[0,:])

34.379999999999995

In [204]:
np.median(np_city[:,0])

1.74

In [205]:
np.std(np_city[:,0])

0.19839687125557198