# NUMPY

In [1]:
import numpy as np

In [2]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [3]:
print(a[0])

[1 2 3 4]


## ARRAY

CREATING ARRAY 

np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

In [4]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
np.zeros(2)

array([0., 0.])

In [6]:
np.empty(2)

array([0., 0.])

In [7]:
print(np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


In [8]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

## Add, Remove dan Sort

np.append()
np.delete()
np.sort()

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)
np.append(arr, [1,2])

[1 2 3 4 5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [12]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [13]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr)
np.sort(arr)

[2 1 5 3 7 4 6 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

### Shape and Size

ndarray.ndim()
ndarray.size()
ndarray.shape()

In [14]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [15]:
array_example.ndim

3

In [16]:
array_example.size

24

In [17]:
array_example.shape

(3, 2, 4)

### Reshape

np.reshape()
numpy.reshape(a, newshape, order)
a =
newshape =
order = 

In [18]:
a = np.arange(6)
print(a)

b = a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


### Convert 1D to 2D

np.newaxis
np.expand_dims

In [20]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [21]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2)
a2.shape

[[1 2 3 4 5 6]]


(1, 6)

In [23]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector)
row_vector.shape

[[1 2 3 4 5 6]]


(1, 6)

In [24]:
# for a column vector, You can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector)
col_vector.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [25]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [26]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
print(b)
b.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [28]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
print(c)
c.shape

[[1 2 3 4 5 6]]


(1, 6)

### Indexing and Slicing

In [29]:
data = np.array([1,2,3])

print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

1
2
[1 2]
[2 3]
[2 3]


In [30]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print (a)

# print all of the values in the array that are less than 5
print(a[a<5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


In [31]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [32]:
# select elements that are divisible by 2

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [33]:
# select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


### Creating Array from Existing Data

slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()

In [34]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

stack them vertically with vstack

In [84]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [85]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [86]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

stack them horizontally with hstack

In [87]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [88]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [89]:
# If you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [94]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
#create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
# Using the copy method will make a complete copy of the array and its data (a deep copy).

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic array operations

Addition, subtraction, multiplication, division, and more

In [97]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [98]:
b = np.array([[1, 1], [2, 2]])
b

#sum the rows
b.sum(axis=0)

array([3, 3])

In [99]:
#sum the columns
b.sum(axis=1)

array([2, 4])

In [100]:
data = np.array([1,2])
data

array([1, 2])

In [101]:
ones = np.ones(2)
ones

array([1., 1.])

In [102]:
data + ones

array([2., 3.])

In [103]:
data * data

array([1, 4])

In [104]:
data / data

array([1., 1.])

## Broadcasting
mekanisme yang memungkinkan NumPy melakukan operasi pada array dengan bentuk berbeda. Dimensi Array harus compatibel.


In [105]:
data * 2

array([2, 4])

### More Array Operation
Maximum, minimum, sum, mean, product, standard deviation, and more

data.max()
data.min()
data.sum()

In [106]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [107]:
A.sum()

4.8595784

In [108]:
A.min()

0.05093587

In [109]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

## Matrices
### Creating Matrices

In [110]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.32311125 0.52140405]
 [0.88479452 0.45059522]
 [0.22190833 0.28054736]]


### Matrix Arithmetic

In [111]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [112]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [113]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [114]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [115]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


### Dot Product

In [116]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [117]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### Matrix Indexing

In [118]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0,1])
print(data[1:3])
print(data[0:2,0])

[[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[1 3]


### Matrix Aggregation

In [119]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [120]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [121]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### Transposing and Reshaping

In [122]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [123]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [124]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [125]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


### N-Dimensional Array

In [128]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [129]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [130]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [131]:
print(np.random.random((4,3,2)))

[[[0.47021121 0.41199088]
  [0.56390494 0.24797531]
  [0.75763272 0.00993149]]

 [[0.71410627 0.47718602]
  [0.45991964 0.90919953]
  [0.52487916 0.50195253]]

 [[0.09648083 0.83644662]
  [0.41900117 0.28760417]
  [0.9911323  0.77742376]]

 [[0.62963788 0.72966456]
  [0.46171064 0.36276055]
  [0.0491177  0.89607166]]]


### Flatten N-Dimensional Array

In [132]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [133]:
# use flatten to flatten your array into a 1D array.

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

### Notes on Numpy Vector

In [134]:
a = np.random.rand(5)
print(a)

[0.50250082 0.37187619 0.73278505 0.69601442 0.42790944]


In [135]:
a.shape # Rank 1 Array

(5,)

In [136]:
print(a.T)

[0.50250082 0.37187619 0.73278505 0.69601442 0.42790944]


In [137]:
print(np.dot(a, a.T))

1.5953154681914032


In [138]:
a = np.random.rand(5,1) # column Vector

In [139]:
print(a.T)

[[0.99780714 0.64692202 0.74240321 0.69398089 0.45536983]]


In [140]:
print(np.dot(a, a.T))

[[0.99561909 0.64550341 0.74077522 0.69245909 0.45437126]
 [0.64550341 0.4185081  0.48027698 0.44895152 0.29458877]
 [0.74077522 0.48027698 0.55116253 0.51521364 0.33806802]
 [0.69245909 0.44895152 0.51521364 0.48160947 0.31601796]
 [0.45437126 0.29458877 0.33806802 0.31601796 0.20736168]]


In [141]:
a = np.random.rand(1,5) # row Vector

In [142]:
print(a)

[[0.61010725 0.76088926 0.82006288 0.79275013 0.05444313]]


# TipsPy

In [144]:
a = np.random.rand(5)
print(a)

[0.85874726 0.15839461 0.32376564 0.15940044 0.94980068]


In [145]:
print(a.T)

[0.85874726 0.15839461 0.32376564 0.15940044 0.94980068]


In [146]:
print(np.dot(a, a.T))

1.7948897244900475


begitu pula dengan row vector

In [148]:
a = np.random.rand(1,5) #row vector

In [149]:
print(a)

[[0.61681257 0.56858505 0.70512928 0.55432274 0.57730843]]


# Introduction to Phyton for Data Analys

- Analisa data
- Analisa data dengan python
- library yg banyak digunakan (Numpy dan Pandas)
- Analisis Data dengan Numpy
- Analisis Data dengan Pandas

mengeksplorasi dan mengomunikasikan pola-pola yg terdapat pada data. khususnya pada area yang kaya informasi. 
mengubah data menjadi insight untuk mengomunikasikan data dan membuat keputusan.
bertujauan untuk mendapatkan keputusan dan hasil yang lebih baik. #dari tebak-tebakan.

Analisis data itu penting berdasarkan analisa. dengan statistik, metode penelitian, dll.
kenapa pakai python???
open source, interpreted, high level language & provides great approach for object-oriented programming. (bahasanya lebih dikenal manusia : print, max, min, dll)
salah satu bahasa pemrograman terbaik yg dapat digunakan oleh data scientist.
(bukalapak, tokped, gojek)
menyediakan berbagai library untuk matematik, statistika, scientific function, dan libraries untuk data science.

# NUMPY

Digunakan untuk data matrix/array
library pada python yang bekerja untuk array
- Aljabar Linear
akronim dari Numerical Python

## ARRAY

- Array dikenal juga dikenal dengan matrix n dimensi. 
- Tipe data terstruktur yang penyimpan value dengan tipe data sama
- Dimulai dari 0, 1, 2, dst.
- memiliki beberapa ukuran 1D, 2D, dst

Array 1 Dimensi : representasi dari vektor
Array 2 Dimensi : matrix

In [4]:
import numpy as np

Kenapa menggunakan numpy??
- array 50x lebih cepat dari list
- memiliki lebih banyak function pendukung dalam data science (split dll)

Cara membuat array :

In [5]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12], [13,14,15], [16,17,18]],
    [[19,20,21], [22,23,24],[25,26,27]]
]

In [10]:
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

np.arange : angka berurutan dg jarak tertentu
start = angka awal
stop = angka akhir
step = jarak antarlangkah di dalamnya
dalam contoh : 
start : 0
stop : 11
step : 2

In [40]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [42]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.eye(4)    #matrix identitas

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
np.linspace (0, 10, 3)    #parameter : start, end, num #kalau udah tau nilai

array([ 0.,  5., 10.])

In [45]:
np.linspace(0,10,50)   #jarak 0-10 berjumlah 50

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [46]:
np.random.rand(2)  #membuat array berisi angka random

array([0.47032102, 0.63326325])

In [47]:
np.random.rand(5,5)

array([[0.68408123, 0.57145429, 0.86524912, 0.6324731 , 0.37731357],
       [0.55216151, 0.82203471, 0.240105  , 0.45549304, 0.86509844],
       [0.29175578, 0.49796298, 0.34543661, 0.23227939, 0.11355826],
       [0.72582675, 0.01323363, 0.23845381, 0.52597395, 0.49925344],
       [0.80087381, 0.8031684 , 0.80074168, 0.55812471, 0.45443002]])

In [48]:
np.random.randn(2) #membuat array berisi angka random berdistribusi normal

array([ 0.4244842 , -1.05645159])

In [82]:
x= np.random.randn(5,5)
x

array([[ 1.15501597,  0.44618495,  0.22238363, -0.5728046 ,  0.63860725],
       [ 0.59440402,  0.75412964,  0.2283787 , -1.70023478, -1.09624466],
       [ 0.63569192,  1.38182291,  1.06087622,  0.62372402,  0.75619275],
       [-0.86694854,  0.04659983, -1.65645622, -0.08949859, -1.11510217],
       [-0.16877497,  0.06367449,  0.07553708,  0.6856211 ,  1.52001199]])

In [83]:
x.astype(int) #menjadikan tipe data 

array([[ 1,  0,  0,  0,  0],
       [ 0,  0,  0, -1, -1],
       [ 0,  1,  1,  0,  0],
       [ 0,  0, -1,  0, -1],
       [ 0,  0,  0,  0,  1]])

In [51]:
np.random.randint(1,100) 

#menghasilkan array berisikan angka integer acak, parameter 3 : angka acak

92

In [52]:
np.random.randint(1,100,10)

array([26, 83, 35, 77, 71,  6,  5, 43, 53, 87])

di atas digunakan untuk machine learning, data dummy 

## Array Attributes and Methods
### Shape
digunakan untuk melihat ukuran array di setiap dimensinya

In [14]:
my_list = [1, 2, 3]
array_1d = np.array(my_list)

my_list2 = [[1,2,3], [4,5,6], [7,8,9]]
array_2d = np.array(my_list2)

my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12], [13,14,15], [16,17,18]],
    [[19,20,21], [22,23,24],[25,26,27]]
]
array_3d = np.array(my_list3)

In [15]:
array_1d.shape

(3,)

In [16]:
array_2d.shape

(3, 3)

In [17]:
array_3d.shape

(3, 3, 3)

### Reshape

In [21]:
arr = np.array([ 0, 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
#vector
arr.shape

(25,)

In [23]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [24]:
arr.reshape(1,25).shape

(1, 25)

In [25]:
arr.reshape(5,5)  #harus sesuai dengan faktor dari shape nya

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [27]:
arr.reshape(25,1).shape

(25, 1)

In [28]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
array_2d.reshape(-1).shape

(9,)

In [30]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [31]:
array_3d.reshape(-1).shape

(27,)

In [32]:
arr.reshape(-1)  #mengembalikan ke bentuk awal

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Min, Max, argmax, argmin

In [35]:
ranarr = np.array([ 10, 12, 41, 17, 49, 2, 46, 3, 19, 39])
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [36]:
ranarr.max()

49

In [37]:
ranarr.argmax()

4

In [38]:
ranarr.min()

2

In [39]:
ranarr.argmin()

5

In [64]:
arr.dtype

dtype('int32')

mengetahui tipe data penting untuk menentukan teknik analisis yang digunakan

In [41]:
arr1 = np.linspace(0,10,10)
arr1

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [42]:
arr1.dtype

dtype('float64')

## Array Dimension
### Indexing dan Selection


Indexing pada array akan mengikuti dimensi pada arraynya.
1 dimensi : kaya list
2 dimensi : vertikal = kolom, horizontal = baris
3 dimensi : axis 0, axis 1, axis 2

#### Index multiarray 1 dimensi

In [43]:
import numpy as np

In [45]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Bracket indexing and selection

In [66]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr[8]

9

In [46]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [48]:
arr[0:10:2]

array([0, 2, 4, 6, 8])

#### Slicing

dalam slicing array apabila mengganti di copy data, maka data awal juga berubah

In [49]:
arr[0:5] = 100

In [50]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [53]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [54]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing 2D Array

In [57]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

indexing

In [58]:
arr_2d[1]

array([20, 25, 30])

In [59]:
arr_2d[1],[0] #bukan

(array([20, 25, 30]), [0])

In [60]:
arr_2d[1][0]

20

In [61]:
arr_2d[1,0]

20

Slicing

In [62]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [63]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [64]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

Fancy Indexing
= memilih elemen array

In [66]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
[arr[2],arr[9],arr[5]]

[2, 9, 5]

In [68]:
arr[[2,5,9]]

array([2, 5, 9])

In [69]:
arr[[2,9,5]]

array([2, 9, 5])

In [70]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [71]:
arr_2d[[0,2]]

array([[ 5, 10, 15],
       [35, 40, 45]])

# Conditional Selection

In [73]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [76]:
bool_arr = arr>4

In [77]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [78]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [79]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
x=2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

FINISH DAY 4

# PANDAS

Tools yang sangat sempurna untuk wragling
2 structure
1. series : menyimpan data 1 dimensi
2. dataframe : menyimpan data 2 dimensi